# Generated by Django 5.0.6 on 2024-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name='Name'
                    )
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Creation date'
                    )
                ),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
    ]
